### PR TITLE
Formatting + Netherlands rename

### PR DESCRIPTION
**Pull request by bram-pkg**
"Netherlands The" is a very weird way to name Netherlands, see https://en.wikipedia.org/wiki/Netherlands

I hope this can be changed, I renamed it manually now using the following command:
```sql
UPDATE countries SET name = "Netherlands" WHERE id = 155;
```

### CODE REVIEW

**Comment by bram-pkg** [comment]
I agree, but I think it'd be good to keep the English naming consistent.
I'm Dutch, but am using Crater for invoicing to countries abroad.

**Comment by mohitpanjwani** [comment]
I agree with you but there’s no reason to change the formatting of the whole file for this small change. It would be better if this PR was just a 1 word change compared to 495 lines being changed.

**Comment by bram-pkg** [comment]
I can revert that, if you think it's needed. But I don't think formatting the code is a step backwards?

**Comment by bram-pkg** [comment]
Reverted the formatting.

**Pull request merged**
