### PR TITLE
🌐Update: support Thai language

### PR DESCRIPTION
**Pull request by ritthikrairw**
## 🌐Update: support Thai language

This update adds Thai language support to the crater application, which includes the frontend and PDF languages.

### CODE REVIEW

**Review by klementj — COMMENTED** [review]
Went through all the files except the locale/th.json. Looks good to me except two requests/questions:
1. Maybe place the font files in the same directory as the Poppins font. So move from public/fonts to where the other fonts currently resides public/**build**/fonts. Consider renaming the files to follow the same naming convention with - instead of space.
2. What's up with the storage/fonts/index.php file?

**Comment by ritthikrairw** [comment]
> Went through all the files except the locale/th.json. Looks good to me except two requests/questions:
> 
> 1. Maybe place the font files in the same directory as the Poppins font. So move from public/fonts to where the other fonts currently resides public/**build**/fonts. Consider renaming the files to follow the same naming convention with - instead of space.
> 2. What's up with the storage/fonts/index.php file?

1. Sure, I'll rename and move the fonts in the same directory as the Poppins font. (I'm not sure if Thai language will work on PDFs, )

2.  `storage/fonts/index.php` I simply create the fonts directory in case, when running the application, Laravel does not automatically create this directory and returns an error `storage/fonts` not found.

I appreciate your reviewing my requests, and I thank you for your feedback. 🙂

**Comment by ritthikrairw** [comment]
Hi @klementj,

I've moved fonts to `resources/static/fonts/` and removed the `index.php` in `storage/fonts/index.php` I realize that no need for this.

Please try to review, if anything is wrong and needs to change or fix, I'm happy to help. 🙂

**Comment by mohitpanjwani** [comment]
Thanks a lot for the contribution @ritthikrairw & @klementj for reviewing it. 

We're currently reviewing this PR.

So far it looks great 👍

**Comment by mohitpanjwani** [comment]
There's a weird issue with dompdf on this PR. 

I got an `fopen` error which went away after creating an empty `fonts` folder under `resources` folder.

**Comment by ritthikrairw** [comment]
@mohitpanjwani  I've added `.gitkeep` in `storage/fonts/` to pre-create the `fonts` directory (same problem as previously), So, right now the dompdf can be able to access fonts cache from `storage/fonts/`

**Pull request merged**
