### PR TITLE
Fixing/Adding translations in components, vue, controller

### PR DESCRIPTION
**Pull request by agencetwogether**
Hello, I'm falling in love about this project. 😊
And I would like to contribute by helping in particular to correct untranslated, missing or hard-coded elements.

That's why I made some commits to do this.
I hope these commits can help community and that they will be integrated to the next release.

To working properly, I started from version 6.0.6, I tried to correct each local language file in which keys were missing (compared to the English reference version).
For each translation carried out, all the language files have been updated.

Of course, each added key will have to be translated into the language concerned 

Thanks again for this crazy project

**More details about commits :** 
- Months below lines in **Dashboard** and **Customers** views are now in language defined by locale inside `config/app.php`
- Data table is now localized
- **Search bar** placeholder and **Confirm password** label (customers views in admin) are fixed to use translation
- Add missing keys in `ko.json` and `pt-br.json`
- Add translation for **This year** and **Previous year** in drop down above _Charts_
- Add news keys in locales files according missing translations for next commits (below this one)
- **Customer portal menu** is working now with translations (due to missing option to choose a language in customer settings portal, to be able to have portal in locale, you have to set this on in `ressources/scripts/Crater.js`)
- Tooltip to **Copy in clipboard** works with translations
- **Sign up and get token** button working now with translations
- **Limit by** and **Frequency** dropdowns in _Recurring invoices_ are now translated
- **Amount Due** below Invoice dropdown in _Payment section_ is now translated
- **Report type** dropdown in _Reports section_ is now translated
- Add translation to **BaseFileUploader**
- Add translation to **BaseMultiselect**
- Add translation to **BaseDatePicker**
- Add news keys in locales files according missing translations for next commits (below this one)
- Translations everything about **Estimates** (_Admin and Customer portal_) using locale
- Translations everything about **Invoices** (_Admin and Customer portal_) using locale
- Translations everything about **Recurring invoices** (_Admin and Customer portal_) using locale
- Translation for **Type** dropdown in _Note Modal_
- Remove some hardcoded texts by replacing them to locale
- Improve stats in **Dashboards** (_Admin and Customer portal_) with singular/plural (see locale files)
-  Remove some hardcoded texts for Payments by replacing them to locale

### CODE REVIEW

**Comment by caiodigioia** [comment]
That's awesome! How can I test the changes on my website?

**Comment by agencetwogether** [comment]
> That's awesome! How can I test the changes on my website?

Until these fixes are incorporated in a future version, you can add the changes to your files if you wish, and republish the assets with yarn build command

**Comment by mohitpanjwani** [comment]
This PR is really well done.

Thanks for the contribution @agencetwogether 

So far it's looking really good but I still need to test this a bit more before merging it. I'll update here by weekend 👍

**Comment by azaricstefan** [comment]
@agencetwogether huge thanks for this effort!!!!

**Comment by azaricstefan** [comment]
@mohitpanjwani , @agencetwogether 
I tested the translations. This is still a bug #1041.

**Comment by thalesog** [comment]
Bump!
Can we get this merged?

**Comment by azaricstefan** [comment]
@mohitpanjwani @agencetwogether bump ++

**Pull request closed without merging**
