### PR TITLE
Added Invoice time option

### PR DESCRIPTION
**Pull request by troky**
Mentioned in https://github.com/crater-invoice/crater/issues/445

### CODE REVIEW

**Comment by izubak** [comment]
I tried to install your PR but cant find the option to enable the time.

**Comment by troky** [comment]
it on admin/settings/preferences page

2023-01-14 12_11_36-Crater - Self Hosted Invoicing Platform

... maybe it shoud go elsewhere but for now I put i here.

**Comment by izubak** [comment]
Sorry. I had to run npm run build. I see it now in preferences but I dont see it in the invoice. Do I need to use a special Blade variable to show it? Or do I need to run something else?

**Comment by troky** [comment]
Fixed that now.

**Pull request closed without merging**
